### ISSUE TITLE
Different bullet style for Title line

### ISSUE THREAD

**Issue by akicebear** [GitMurf/roam-highlighter#67] opened 2020-10-06 00:52 UTC
In the settings it is possible to set a custom bullet style. Could we please have a custom bullet style (or front matter) for the title? 

What I’d like is for the title to be in a checkmark (- [ ]) and the highlights to be regular bullets (-). Thanks for considering this, awesome tool.

**Comment by GitMurf** [comment] 2020-10-06 01:09
@akicebear Interesting idea. So by title do you mean the line with the web address? So the top level parent of all the highlights?

**Comment by GitMurf** [comment] 2020-10-06 01:10
And what did you mean by "(or front matter)"?

**Comment by akicebear** [comment] 2020-10-06 06:06
Yes, so for example on this page, highlighting your comment, it would look like this:

- [ ] [Different bullet style for Title line · Issue #67 · GitMurf/roam-highlighter](https://github.com/GitMurf/roam-highlighter/issues/67)
    - Interesting idea. So by title do you mean the line with the web address? So the top level parent of all the highlights?

Sorry if using the term "front matter" was confusing - another similar plugin I've tried, MarkDownload, allows you to include whatever text you'd like before (front matter) and/or after (back matter) the standard link and copy of article. My mistake using their terminology; you described the desired behavior correctly.

**Comment by GitMurf** [comment] 2020-10-25 00:41
Duplicate of #79

**Comment by GitMurf** [comment] 2020-10-25 00:42
Merging with #79

**Closed by GitMurf** 2020-10-25 00:42 UTC
Labels: enhancement
