### ISSUE TITLE
Mouse Click Highlight not working

### ISSUE THREAD

**Issue by david-ps** [GitMurf/roam-highlighter#48] opened 2020-07-10 09:39 UTC
Just installed latest Chrome Extension 1.9.7.2 
Can only highlight using Crtl-X, 
Mouse/cursor does not highlight ie no yellow and no copy to sidebar. 
Have tried on Chrome and Edge latest versions.

**Comment by GitMurf** [comment] 2020-07-10 12:51
Auto highlight by mouse drag is not a feature of my highlighter... yet. Right now ctrl+X is only option.

**Comment by GitMurf** [comment] 2020-10-22 03:20
Duplicate of #71

**Closed by GitMurf** 2020-10-22 03:20 UTC

**Comment by GitMurf** [comment] 2020-10-30 06:31
@david-ps it has been implemented! Please check out the new update and let me know what you think? Thanks!
