### ISSUE TITLE
Pass through common academic publication metadata as tokens

### ISSUE THREAD

**Issue by DmitriR** [GitMurf/roam-highlighter#126] opened 2021-02-07 09:12 UTC
... at least the citation_* namespace; possibly others as well, prism in particular. 

Simply passing them through will be excellent. 

No need to integrate / coerce into a single namespace, **except** that the two de-facto universal IDs: DOI and PMID (PubMed ID); these probably deserve their own standard tokens, regardless of how they are represented on the page. 

The utility: the header / title line could be configured to include publication year and authors, and outgoing links not only to the source page but to the "canonical" home page (DOI crossref) and to the PubMed page. The DOI link could be intercepted locally to open the corresponding PDF. 

Metadata tags are described [here](http://div.div1.com.au/div-thoughts/div-commentaries/66-div-commentary-metadata)

**Comment by GitMurf** [comment] 2021-02-19 08:16
@DmitriR I am merging this with another issue opened similar to this. I put a few ideas I'm working on in it.

**Comment by GitMurf** [comment] 2021-02-19 08:18
Duplicate of #119

**Closed by GitMurf** 2021-02-19 08:18 UTC
Labels: duplicate
