### ISSUE TITLE
Ability to turn off links

### ISSUE THREAD

**Issue by K-293** [GitMurf/roam-highlighter#43] opened 2020-06-25 04:57 UTC
Hey man! Lovely plugin. Been using it with Obsidian for a while Now.

I use it to take notes off Wikipedia articles. It would be helpful if you could add the feature to turn off links. I would prefer not to have links in my note that arent added by me - I usually take notes off webpages and I will have to manually delete links from extracts - this takes a lot of time.

Thanks and regards!

**Comment by mrcasals** [comment] 2020-06-25 07:40
Seems like it's related to #32 😄

**Comment by GitMurf** [comment] 2020-06-25 15:08
> Seems like it's related to #32 😄

And also #38 :-)

@mrcasals I have not forgotten about you! Just swamped at work so haven't made any updates in last few weeks. It is at the top of the list though. Hoping to get some time this weekend.

**Comment by GitMurf** [comment] 2020-06-25 15:12
Duplicate of #32

**Comment by GitMurf** [comment] 2020-06-25 15:32
Duplicate of #32

**Closed by GitMurf** 2020-06-25 15:32 UTC
